service:
  name: test-service

provider:
  name: aws
  stage: ${self:custom.stage}
  runtime: nodejs10.x
  memorySize: 1024
  region: us-west-2

custom:
  stage: ${opt:stage, 'dev'}

functions:
  test-function:
    handler: index.handler